// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: testdata/protoexample/test.proto

package protoexample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestMessage is a simple message for testing protobuf functionality
type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_testdata_protoexample_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protoexample_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protoexample_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TestMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// UserProfile represents a user profile
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata      *TestMessage           `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_testdata_protoexample_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protoexample_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_testdata_protoexample_test_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserProfile) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserProfile) GetMetadata() *TestMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_testdata_protoexample_test_proto protoreflect.FileDescriptor

const file_testdata_protoexample_test_proto_rawDesc = "" +
	"\n" +
	" testdata/protoexample/test.proto\x12\btestdata\"[\n" +
	"\vTestMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xa8\x01\n" +
	"\vUserProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x121\n" +
	"\bmetadata\x18\x05 \x01(\v2\x15.testdata.TestMessageR\bmetadataB4Z2github.com/gonoleks/gonoleks/testdata/protoexampleb\x06proto3"

var (
	file_testdata_protoexample_test_proto_rawDescOnce sync.Once
	file_testdata_protoexample_test_proto_rawDescData []byte
)

func file_testdata_protoexample_test_proto_rawDescGZIP() []byte {
	file_testdata_protoexample_test_proto_rawDescOnce.Do(func() {
		file_testdata_protoexample_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_protoexample_test_proto_rawDesc), len(file_testdata_protoexample_test_proto_rawDesc)))
	})
	return file_testdata_protoexample_test_proto_rawDescData
}

var file_testdata_protoexample_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testdata_protoexample_test_proto_goTypes = []any{
	(*TestMessage)(nil), // 0: testdata.TestMessage
	(*UserProfile)(nil), // 1: testdata.UserProfile
}
var file_testdata_protoexample_test_proto_depIdxs = []int32{
	0, // 0: testdata.UserProfile.metadata:type_name -> testdata.TestMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testdata_protoexample_test_proto_init() }
func file_testdata_protoexample_test_proto_init() {
	if File_testdata_protoexample_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_protoexample_test_proto_rawDesc), len(file_testdata_protoexample_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_protoexample_test_proto_goTypes,
		DependencyIndexes: file_testdata_protoexample_test_proto_depIdxs,
		MessageInfos:      file_testdata_protoexample_test_proto_msgTypes,
	}.Build()
	File_testdata_protoexample_test_proto = out.File
	file_testdata_protoexample_test_proto_goTypes = nil
	file_testdata_protoexample_test_proto_depIdxs = nil
}
