name: golangci-lint

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          # NOTE: Keep this in sync with the version from go.mod
          go-version: "1.23.x"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
