name: Run govulncheck

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  govulncheck-check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: false

      - name: Install Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Govulncheck
        run: govulncheck ./...
